### PR TITLE
Add "started_charging" trigger in flow

### PR DESCRIPTION
**Pull request by Timvdv**
Because the Webhook was not implemented (😢), I created a check on the status change when the status is "cleaning" or "stopped" and then changes to "charging". the flow triggers.

### CODE REVIEW

**Comment by Timvdv** [comment]
@RobinBol

**Comment by RobinBol** [comment]
Hi Tim, thanks for the PR, I went ahead, did a quick test and merged your PR. Will release the update in the app store today. 

P.S. did I miss something in the implementation of your API (with regard to your comment on the webhook)?

**Comment by Timvdv** [comment]
@RobinBol Thanks! Looking forward to it.

You can setup a webhook while configuring the Thinking Cleaner. This way you don't have to use a interval to poll for changes. When this is implemented it will also give extra 'when' trigger opportunities. For example: when the roomba leaves / enters the docking station. This is not possible at the moment because of the delay in the interval. Also the plugin will feel a lot more responsive.

**Comment by Timvdv** [comment]
@RobinBol What's the status? I still see the old 2.0.4 version in the store.

**Comment by RobinBol** [comment]
My bad, still had to publish it.. By the way, if you think the app can be improved using the webhook, feel free to contribute! I would do it myself, but at the moment there are more urging tasks for me, so it would not be implemented by us any time soon unfortunately.

**Comment by Timvdv** [comment]
@RobinBol Yeah! I know :) I don't actually own a Homey so I can only do this when I'm at my parents house.

I see the new version is now in the app store! Thanks.

**Pull request merged**
